version: "3.8"
services:
  proxy:
    build: ./proxy
    ports:
      - "3000:3000"
  front:
    build:
      context: ./front
      args:
        VITE_API_BASE_URL: https://rates-converter.onrender.com/
    environment:
      - VITE_API_BASE_URL=https://rates-converter.onrender.com/
    ports:
      - "4173:4173"
    depends_on:
      - proxy